version: '2'
services:
  openldap:
    container_name: openldap
    build: ./openldap
    ports:
      - "1389:389"
  keycloak:
    container_name: keycloak
    build: ./keycloak
    ports:
      - "8180:8080"
    depends_on:
      - openldap

